---
- name: Create project directory
  file:
    path: /opt/wordpress
    state: directory
    mode: '0755'

- name: Synchronize all files including hidden ones
  synchronize:
    src: "files/"
    dest: "/opt/wordpress/"
    recursive: yes

- name: Install pip
  apt:
    name: python3-pip
    state: present
  become: yes

- name: Install required Python packages
  pip:
    name:
      - docker
    state: present
  become: yes

- name: Deploy WordPress with Docker Compose
  community.docker.docker_compose_v2:
    project_src: /opt/wordpress/
    state: present
    project_name: wordpress
    timeout: 300
  register: compose_result
#
#- name: Debug Docker Compose result
#  debug:
#    var: compose_result
#
#- name: Check container status
#  community.docker.docker_container_info:
#    name: "{{ item }}"
#  loop:
#    - wordpress-db-1
#    - wordpress-wordpress-1
#    - wordpress-nginx-1
#  register: container_info
#
#- name: Display container status
#  debug:
#    msg: "Container {{ item.container.Name }} is {{ item.container.State.Status }}"
#  loop: "{{ container_info.results }}"