---
- name: Install fail2ban
  apt:
    name: fail2ban
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Install fail2ban
  yum:
    name: fail2ban
    state: present
  when: ansible_facts['os_family'] == 'RedHat'

- name: Ensure fail2ban is started and enabled
  service:
    name: fail2ban
    state: started
    enabled: yes

- name: Configure jail.local for SSH
  copy:
    dest: /etc/fail2ban/jail.local
    content: |
      [DEFAULT]
      bantime  = 600
      findtime  = 600
      maxretry = 3

      [sshd]
      enabled = true
      port    = ssh
      logpath = %(sshd_log)s
      backend = %(sshd_backend)s
  notify: Restart fail2ban
