---
- name: Install iptables-persistent if not present (Debian/Ubuntu)
  apt:
    name: iptables-persistent
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == 'Debian'

- name: Install iptables-services if not present (RedHat/CentOS)
  yum:
    name: iptables-services
    state: present
  when: ansible_facts['os_family'] == 'RedHat'

- name: Allow HTTP traffic
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 80
    jump: ACCEPT
  notify: Save iptables rules

- name: Allow HTTPS traffic
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 443
    jump: ACCEPT
  notify: Save iptables rules
