services:
  wordpress:
    build: .
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress

  nginx:
    image: nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - /opt/wordpress/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/1246138045414244484-students.devboxops.xyz/self_signed.crt:/etc/letsencrypt/1246138045414244484-students.devboxops.xyz/self_signed.crt
      - /etc/letsencrypt/1246138045414244484-students.devboxops.xyz/self_signed.csr:/etc/letsencrypt/1246138045414244484-students.devboxops.xyz/self_signed.csr,
      - /etc/letsencrypt/1246138045414244484-students.devboxops.xyz/self_signed.key:/etc/letsencrypt/1246138045414244484-students.devboxops.xyz/self_signed.key,

      - wordpress_data:/var/www/html
    depends_on:
      - wordpress

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password

volumes:
  wordpress_data:
  db_data: