---
- name: Копировать публичный SSH-ключ на хосты для созданных пользователей
  authorized_key:
    user: "{{ username }}"
    key: "{{ lookup('file', ssh_keys) }}"
    state: present
  become: true

- name: Configure SSH settings
  block:
    - name: Ensure SSH password authentication is disabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
      register: ssh_password_auth

    - name: Ensure SSH key-based authentication is enabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'
        state: present
      register: ssh_pubkey_auth

    - name: Ensure ChallengeResponseAuthentication is disabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?ChallengeResponseAuthentication'
        line: 'ChallengeResponseAuthentication no'
        state: present
      register: ssh_challenge_auth

    - name: Ensure the new SSH port is configured
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Port'
        line: 'Port {{ ssh_port }}'
        state: present
      register: ssh_port_change
  vars:
    ansible_become: yes

- name: Set new SSH port for Ansible
  set_fact:
    ansible_ssh_common_args: '-o Port={{ ssh_port }}'
  when: ssh_port_change | default(false)

- name: Check if SSH config changed
  set_fact:
    ssh_config_changed: "{{ ssh_password_auth.changed or ssh_pubkey_auth.changed or ssh_challenge_auth.changed or ssh_port_change.changed }}"
  notify: Restart SSH

- name: Allow new SSH port through firewall (if using ufw)
  ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp
  when: ansible_facts['os_family'] == 'Debian'
  notify: Reload ufw

- name: Allow new SSH port through firewall (if using firewalld)
  firewalld:
    port: "{{ ssh_port }}/tcp"
    permanent: yes
    state: enabled
  when: ansible_facts['os_family'] == 'RedHat'
  notify: Reload firewalld