---
- hosts: all
  become: yes
  roles:
    - role: access_configuration
      tags: access

      ssh_port: 2220

      configure_ssh: true
      configure_firewall: true
      configure_fail2ban: true

    - role: nginx_config
      tags: nginx

    - role: docker_install
      tags: docker

    - role: wordpress_deploy_docker_compose
      tags: wordpress
