---
- hosts: all
  become: yes
  roles:
    - role: access
      tags: access

      port: 2220

      configure_ssh: true
      configure_firewall: true
      configure_fail2ban: true

    - role: nginx
      tags: nginx

    - role: docker
      tags: docker

    - role: wordpress
      tags: wordpress
